### ISSUE TITLE
Full copy for 'About' page

### ISSUE THREAD

**Issue by Zacker** [covid-projections/covid-projections#100]
Here is the doc with About page copy:

https://docs.google.com/document/d/11lyFnvgt90geIMy8xMMB6Et2JvfwvBmuKLBmsGJhuEo/edit?ts=5e76ebe6#

Please confirm with me before you publish. There will be some last-minute edits.

**Comment by Fiskell** [comment]
Closed by: https://github.com/covid-projections/covid-projections/pull/105 and https://github.com/covid-projections/covid-projections/pull/107
