### ISSUE TITLE
Optimize text sizes, chart height on mobile web

### ISSUE THREAD

**Issue by rachelrf** [covid-projections/covid-projections#117]

**Comment by zjrosen1** [comment]
See the Figma for reference https://www.figma.com/file/UUCr3ZpwaPV4o1KuGdSCNl/Covid?node-id=3%3A0

**Comment by igorkofman** [comment]
How's this going?  I know @arjun-ltse started on this as well but not sure if it's being actively worked on.  Can you guys sync @arjun-ltse @rachelrf ?

**Comment by rachelrf** [comment]
sure thing. @arjun-ltse, do you want to get your change into a good state and land it, and then I can pick up this issue from there?

**Comment by arjun-ltse** [comment]
@rachelrf I'm very limited with time this week. I will have an hour or two tonight. I'll actually try to break it out into smaller PRs that are more focused and can be taken over individually.

**Comment by arjun-ltse** [comment]
@rachelrf @zjrosen1 Unfortunately not going to be able to get to this.

The biggest issue I was trying to resolve is the endorsements grid. I can create a new ticket. But can't fix, tonight at least.

**Comment by rachelrf** [comment]
@arjun-ltse I can work on this tomorrow evening, just so we're on the same page, can you update with:

1) the status of anything in progress, if you already got started
2) whether you have time to keep working on it or would rather hand it off 

Either is fine, but do please let me know before tomorrow evening so that we can avoid any duplicate work :)

**Comment by arjun-ltse** [comment]
@rachelrf Thanks for that. And apologies for not being able to continue on this.

**For 1:**
I'd suggest to close my PR and start fresh. I realize it wasn't clear what this task entails regarding the design (eg. Is part of this to wrap the page titles in black boxes)? My PR got too convoluted and it was trying to tackle too many things:

- Typography styles
- Global breakpoints
- Endorsements on mobile (ref #149)
- Padding/margins on mobile

None of which were resolved enough to merge.

You can review the PR for reference. You can see I was trying to use a global value for breakpoints. But the reality is that there are 4 different style systems going on here (inline, SCSS, materialUI, and CSS).

Would be good to check with @szhu about #149 to avoid duplicate work.

**For 2:**
I don't have time this week to keep working on this, so you can for sure take this over!

**Comment by szhu** [comment]
@rachelrf fyt I made #149 to make endorsements responsive
