### ISSUE TITLE
Site appears blocked by Meetcircle

### ISSUE THREAD

**Issue by jredding** [covid-projections/covid-projections#133]
https://twitter.com/gdemet/status/1241857608920764418

![Screen Shot 2020-03-22 at 6 54 37 PM](https://user-images.githubusercontent.com/3867620/77263405-9a59cc00-6c6e-11ea-88bb-50a16b49fa95.png)

**Comment by igorkofman** [comment]
@jredding - can you see if it's working for him now?

**Comment by jredding** [comment]
apologies for letting this go so long. Yes, it's confirmed as closed. Working now - my gut tells me the same upstream provider that services comcast also serves meetcircle
