### ISSUE TITLE
Users uncertain of definitions of interventions

### ISSUE THREAD

**Issue by raygilbert** [covid-projections/covid-projections#138]
Got feedback from some folks that they would like to see definitions of the interventions on the state pages so they can better understand w/out having to google 1 or more definitions.   Maybe a tool tip or sidebar w/defs?

**Comment by crwilcox** [comment]
New front page has a definition to the right of the map. Is this sufficient? 
![image](https://user-images.githubusercontent.com/638797/77475812-9cd73580-6dd6-11ea-8e74-0236f26d6b85.png)

**Comment by raygilbert** [comment]
Initial feedback is good.  Will continue to solicit inputs.
