### ISSUE TITLE
State Map Tooltip doesn't Render

### ISSUE THREAD

**Issue by apeterson7** [covid-projections/covid-projections#1382]
## summary
State Map Tooltip doesn't Render.  County Map functionality hasn't been effected

## environment
*(device, browser, mobile / web)*

## screenshot
*(you can copy/paste images directly in)*

**Comment by mikelehen** [comment]
Ooops!  Broken by https://github.com/covid-projections/covid-projections/commit/94ffa2a4b64843fafc4aff94b74fd59f25f0b19d .   Fixed by https://github.com/covid-projections/covid-projections/commit/1c15ef642eaa1247baa913c646fdf22590d0bf03 .

Thanks for the report @apeterson7 !
