### ISSUE TITLE
State page > highlight current intervention 

### ISSUE THREAD

**Issue by zjrosen1** [covid-projections/covid-projections#147]
Once we have the intervention data available highlight the table row that corresponds to the states intervention 

nice to have would also be increasing stroke width of current states intervention line in the chart

**Comment by zjrosen1** [comment]
This work can be started before we have the data

**Comment by crwilcox** [comment]
@zjrosen1 is this separate from the new frontpage? 
![image](https://user-images.githubusercontent.com/638797/77475743-8335ee00-6dd6-11ea-938b-ab8c0db35c38.png)

**Comment by igorkofman** [comment]
yes - it's about highlighting a row in the table on each state page

**Comment by ronakdev** [comment]
<img width="1792" alt="Screen Shot 2020-03-26 at 12 05 19 AM" src="https://user-images.githubusercontent.com/9388431/77619571-b7540080-6ef5-11ea-996e-ecd18bc67f38.png">
I can work on this — are we looking at highlighting the row like this (barring a proper design ofc, I'll try to figma something tomorrow)?

**Comment by igorkofman** [comment]
Not obvious what we want to scenario ranges - will have to be part of a broader re-design
