### ISSUE TITLE
Counties display last search when selecting new state

### ISSUE THREAD

**Issue by apeterson7** [covid-projections/covid-projections#1494]
## summary
When I select a new state from the text search selector, the counties from the last state are not refreshed.

## actual result
![image](https://user-images.githubusercontent.com/14878849/93401309-dce01800-f84f-11ea-9226-f2a3c055cd79.png)
I searched for NY, then DC.  NY counties are still displayed.

![image](https://user-images.githubusercontent.com/14878849/93401459-2cbedf00-f850-11ea-8192-370badc6632f.png)
I searched for Maryland, then Massachusetts.  Maryland counties are still displayed.

## environment
Chrome, Macbook

## screenshot
*(you can copy/paste images directly in)*

**Comment by mikelehen** [comment]
Fixed by #1495.
