### ISSUE TITLE
Add UI AB testing

### ISSUE THREAD

**Issue by rachelrf** [covid-projections/covid-projections#157]
With how quickly we're iterating, it might make some sense to AB test changes using something like https://github.com/hudovisk/react-optimize. @igorkofman @zjrosen1 thoughts?

**Comment by jredding** [comment]
Totally love A/B testing - a few questions on this:
Do we have the bandwidth to review these analytics? 
and what might we want to test?

**Comment by igorkofman** [comment]
Let's use this as soon as we have an experiment we want to run!

**Comment by rachelrf** [comment]
Yeah, I wasn't thinking full data analysis, more like just seeing if things are directionally positive in Google Analytics. A couple of things it might be helpful for:

- new functionality like [this PR](https://github.com/covid-projections/covid-projections/pull/151))
- map and chart changes
- design changes (layout tweaks etc)
- which social media buttons we use
- adding native share sheet for mobile users

**Comment by igorkofman** [comment]
Let's pick this up once we have our first test to change!
