### ISSUE TITLE
Add radio buttons in the email capture box under the email textbox

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#159]
The options should be:
- I am a concerned citizen (default)
- I am a healthcare / government decision maker

**Comment by sarabpj** [comment]
Is there a way to edit the [iframe](https://app.mailjet.com/widget/iframe/1dtU/pXf)?

**Comment by ronakdev** [comment]
@sarabpj you should be able to edit it with mailjet — https://www.mailjet.com/feature/subscription-widget/
