### ISSUE TITLE
Support mapping cities -> counties

### ISSUE THREAD

**Issue by szhu** [covid-projections/covid-projections#161]
When a user searches for a popular city, we need to be able to show data for the county the city is in.

This is just an engineering task and isn't connected to any UI in particular, but just for illustration purposes:
![image](https://user-images.githubusercontent.com/1570168/77364544-cc703a00-6d11-11ea-8375-709061c67b5a.png)

Example way that this could be used: when the user searches for "Seattle", the King County suggestion should be shown.

**Comment by igorkofman** [comment]
amazing - though the screenshot doesn't show it off!

**Comment by crwilcox** [comment]
@szhu is their a PR/Issue for adding search?

**Comment by szhu** [comment]
@crwilcox Not as far as I know. Should I add it?

(I didn't add it yet because I don't know what's the correct threshold for adding feature issues here, and also I didn't want someone to start building it before I got confirmation that it was a good idea.)

**Comment by szhu** [comment]
Found a dataset we can use for city -> county mapping:

https://simplemaps.com/data/us-cities

Note: they require a linkback to this url.

I looked at the dataset and it has everything we need, including columns for:
- City/County/State
- Some cities (like Portland) are in multiple counties -- it has this data as well
- Lat/Long (for showing on map + getting closest city to user)
- Population (for sorting suggestions)

**Comment by crwilcox** [comment]
I was curious about the feature before city -> county mapping. This shows a search by county name. Has that been tracked/pr'd?
