### ISSUE TITLE
Add "sign up to endorse" to endorsements page

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#174]

**Comment by rachelrf** [comment]
@igorkofman any more details on this one/designs? is there a form we want them to fill out?

**Comment by igorkofman** [comment]
Let's just drop in a mailto link with "endorse@covidactnow.org".

**Comment by rachelrf** [comment]
something like this what you had in mind?

<img width="758" alt="Screen Shot 2020-03-25 at 5 46 25 PM" src="https://user-images.githubusercontent.com/11700818/77598995-945b2980-6ec0-11ea-87f0-55fcc3cc6bc5.png">

**Comment by igorkofman** [comment]
perfect!
