### ISSUE TITLE
Louisiana is misspelled when you hover over the state on the homepage map

### ISSUE THREAD

**Issue by Jtensminger** [covid-projections/covid-projections#190]
Louisiana is misspelled when you hover over the state on the homepage map.

**Comment by zjrosen1** [comment]
This is coming from https://github.com/gabidavila/react-usa-map/blob/master/src/data/usa-states-dimensions.json, shouldn't be an issue once we switch maps

**Comment by mikelehen** [comment]
Looks like this is fixed.
