### ISSUE TITLE
Scenario colors differ between chart and table

### ISSUE THREAD

**Issue by raygilbert** [covid-projections/covid-projections#197]
![Screen Shot 2020-03-25 at 4 46 18 PM](https://user-images.githubusercontent.com/714216/77584005-6e318b80-6eb8-11ea-90d4-18af0b7424e6.png)
Example: green is 3 mos shelter in place on the chart, and blue in the Predicted Outcomes table

**Comment by igorkofman** [comment]
More feedback on this from https://en.wikipedia.org/wiki/Anne_Fadiman (!!):

..the colors and wording should match the ones in the scenario chart just below, and they don't:

"Limited action" is the same color as "no action" (red), but they should be phrased the same. Right now they sound like two entirely different scenarios.
"3 months of social distancing" matches both color (yellow) and phrasing, but the punctuation is different, which looks unprofessional. I'd do "3 Months of Social Distancing" (uppercase Distancing).
"3 months of Shelter-in-place" is mint-green up above, and blue below. Also, it's punctuated differently. I'd do "Shelter-in-Place" (hyphens throughout, and uppercase Place).
"3 months of Lockdown" is purple above and bright green below. Probably ok to use Wuhan below and not above, but the unmatched colors are problematic.

--

'Limited action' is the new language.  Colors in the graph are the right colors
