### ISSUE TITLE
Add and surface models for DC, PR and VI in map / search

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#199]

**Comment by rachelrf** [comment]
my Puerto Rican friend is bummed we don't have this so I can take this one on :) do we have models/designs for how we want to surface these? just through the state search?

**Comment by igorkofman** [comment]
@rachelrf  - sorry I missed this.  Are you still able to take this on?

**Comment by rachelrf** [comment]
@igorkofman I can, do we have models/designs?

**Comment by igorkofman** [comment]
@erccarls is working on it
