### ISSUE TITLE
Include a link or button to "claim a county" if you're a public official in that county

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#258]
We should include this in our counties launch (since that's when we'll get the most traffic on these pages probably). It should lead to a Google Form that collects contact info and info about what information they want to update

**Comment by igorkofman** [comment]
It should lead to a Google Form that collects contact info and info about what information they want to update

**Comment by mikelehen** [comment]
Obsolete (should be tracked on roadmap if we want to do this)
