### ISSUE TITLE
Generate a per-state index file for county models that only lists the counties that have models

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#259]
Something like CA.counties.json [{fips, cases, hospitalizations, population}, ...]

**Comment by igorkofman** [comment]
@Fiskell - did you guys make any decisions on what will be in here?

**Comment by Fiskell** [comment]
Not yet

**Comment by mikelehen** [comment]
@ghop02 Anything left to do here, or should we close this?
