### ISSUE TITLE
Use npm instead of yarn.

### ISSUE THREAD

**Issue by dopry** [covid-projections/covid-projections#269]
I don't really see a requirement for yarn here.  Is there a reason were using it over npm?

`yarn` is an additional pre-requisite that developers need to install.,creating impedance to participation
`yarn` isn't needed for react.
`npm` has locks like yarn since npm 5
`npm` has similar performance since npm 5
`npm` provides package security auditing since npm 6

**Comment by szhu** [comment]
In my observations I've noticed that that most js developers seem to use yarn already, so it might be more familiar to them. We can also just ignore `yarn.lock` but people can still keep using yarn if they want.

**Comment by dopry** [comment]
![image](https://user-images.githubusercontent.com/387640/77862543-2ed1aa80-71ea-11ea-88f5-4c91b91066ba.png)

npm is downloaded by 25% more time than yarn, and that is not counting people who get their npm updates with their node downloads which hovers around 1M per week.   I think 'most' is a stretch by objective measures.

Another fact all developers using node have npm installed, only those developers who have opted into yarn have it installed.  

If we're going to contribute anecdotes, I'd say that most developers only install yarn because it's used in react by default and FB goes out of their way to market it.  It is not used very widely in the svelte, vue, or angular, or nodejs communities.
