### ISSUE TITLE
Chart resize issue

### ISSUE THREAD

**Issue by jredding** [covid-projections/covid-projections#28]
When resizing the browser the chart elongates. This occurs if the browser is made larger or smaller.  

To replicate:

1. Navigate to site
2. Choose any state
3. Resize browser

Outcome: Chart elongates upon browser resize 

Desired outcome: Chart size changes proportional to canvas area.

**Comment by jredding** [comment]
Video demonstrating issue:
https://drive.google.com/file/d/1j1htLTFMLFH2mdnrP7My5TryAMsVsECl/view?usp=sharing

**Comment by zjrosen1** [comment]
This does not appear to be happening with highcharts closing for now
