### ISSUE TITLE
Add social media links to the website

### ISSUE THREAD

**Issue by asciimike** [covid-projections/covid-projections#300]
We need to add links to our social media to the footer:
 - https://twitter.com/CovidActNow
 - https://www.facebook.com/covidactnow
 - https://www.instagram.com/covidactnow/

Something like this is sufficient (obviously swapping LinkedIn for Instagram):

![image](https://user-images.githubusercontent.com/2575327/77969549-2be8bf80-72a7-11ea-9eb6-5df69ac19e2f.png)

**Comment by asciimike** [comment]
We should add these links to the "contact" page as well under a `Follow us on Social Media:` header.

**Comment by mikelehen** [comment]
Crazy question, but should we (also) put them in that prominent "Want to stay apprised of COVID projections?" box?
