### ISSUE TITLE
/compare: Add "diff" to comparison page

### ISSUE THREAD

**Issue by davidstrauss** [covid-projections/covid-projections#305]
Three ideas:

- How many days (forward or back) the date of hospital overload occurs
- Impact to total infected population
- Impact to total deaths

**Comment by mikelehen** [comment]
I did some work on this to refactor the loading of all the models up into the top-level CompareModels component: https://github.com/covid-projections/covid-projections/pull/328

@rachelrf has started work on diffing models, so I'm handing this back over to her for now.

Note that my PR is likely going to conflict with stuff in the counties branch, so we'll need to be careful about when / how we merge it.

**Comment by mikelehen** [comment]
[See also https://github.com/covid-projections/covid-projections/issues/296]

**Comment by mikelehen** [comment]
@rachelrf got this working for "hospital overload".  Hooray!  Can play with it at: https://covid-projections-git-rachelrf-issues296.covidactnow.now.sh/compare

I think that branch is kinda' in limbo until all the county stuff lands though.

**Comment by igorkofman** [comment]
Is this mergeable?

**Comment by rachelrf** [comment]
Yep, should be

**Comment by mikelehen** [comment]
Unfortunately there are actually merge conflicts (again).  😭   ModelChart.js is a dangerous file to touch.

@zjrosen1 was looking into it earlier today though and thought he might be able to get it fixed up / merged.

**Comment by rachelrf** [comment]
oh man haha...I can take a look and get it fixed again

**Comment by mikelehen** [comment]
This got merged via #464.  Thank you!

**Comment by mikelehen** [comment]
Oops, reopened.  we now have hospital overload diffing, but not the other 2 yet.

**Comment by rachelrf** [comment]
I can add the other 2 filters as well, call out anything else that would be useful :) @davidstrauss

**Comment by davidstrauss** [comment]
@rachelrf Please feel free to jump on it! The ideas listed were from my meeting notes based on requests from others, so we may need to pull in someone like Max if you'd like more direction on how the "diff" of the impacts should be presented.
