### ISSUE TITLE
Add download functionality for charts

### ISSUE THREAD

**Issue by rachelrf** [covid-projections/covid-projections#316]
Add functionality to download/export our charts.

Potential issue here is that our model is continually updating, so we don't want users to rely on out-dated information. One way to prevent this could be to add a "watermark" with the download date and maybe a disclaimer.

@igorkofman would this be useful functionality?

**Comment by igorkofman** [comment]
We have embeds now!  We're working on a better API that would augment that.  Lmk if you want to get involved in that.  Ping on slack is best!
