### ISSUE TITLE
Endorsement from Donald M. Berwick

### ISSUE THREAD

**Issue by asciimike** [covid-projections/covid-projections#317]
*Name:* Donald M. Berwick, MD, MPP, FRCP

*Title:* Former Administrator, Centers for Medicare and Medicaid Services
President Emeritus and Senior Fellow, Institute for Healthcare Improvement

*LinkedIn:* https://www.linkedin.com/in/don-berwick-46a49380/

*Preferred photo (url, otherwise will use LinkedIn photo):*

**Comment by asciimike** [comment]
See https://github.com/covid-projections/covid-projections/blob/develop/src/enums/endorsers.js

**Comment by jamestamplin** [comment]
Thanks for adding!
