### ISSUE TITLE
"King County" gives bad search results.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-projections#341]
*summary:* When you enter "King County" in the search, the top result is "King County / Snohomish County, WA (47k residents)" which I guess is a weird data artifact combining two different counties.  Among the other results are things like "Licking County / Muskingum County, Ohio (224 residents)". **NOT INCLUDED** in the results is "King County, WA (2.06M residents)".  If I instead search for "King County," (with the trailing comma) then it shows up.

*expected result:* Searching for "King County" should show "King County, WA" as the top result, and probably "King County, TX" as the second result, and probably should not include "licking county", "Hocking County", etc.

*actual result:* "King County, WA" does not show up.

*environment (device, browser, mobile / web):* chrome desktop

*link:* https://staging.covidactnow.org/

*screenshot (you can copy/paste images directly in):*
![image](https://user-images.githubusercontent.com/206364/78210933-82e5c480-7460-11ea-89fa-dc281e4f1232.png)

Search with trailing comma:
![image](https://user-images.githubusercontent.com/206364/78210972-a3158380-7460-11ea-9d50-6729e00ededf.png)

**Comment by mikelehen** [comment]
I think @zjrosen1 has fixed this now, but I'll let him close.

**Comment by jamestamplin** [comment]
Seems to work for me too

cc @zjrosen1 for closure

**Comment by mikelehen** [comment]
Yeah. I've verified as well.  Closing.
