### ISSUE TITLE
Search surfaces "merged" counties with incorrect populations.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-projections#342]
*summary:* If I search for "King County" the top result is "King County / Snohomish County, WA" with a listed population of 47k, which makes no sense since King County's population is ~2M.  If I click it, I get a "valid" page (https://staging.covidactnow.org/state/WA/county/king_county_snohomish_county) with a model chart. But I don't know what the chart is being driven from.  King County data? Snohomish data? Both?

*expected result:* No "Foo County / Bar County" entries.

*environment (device, browser, mobile / web):* chrome desktop

*link:* https://staging.covidactnow.org/state/WA/county/king_county_snohomish_county

*screenshot (you can copy/paste images directly in):*
![image](https://user-images.githubusercontent.com/206364/78211669-78c4c580-7462-11ea-95ee-2d22c10622f4.png)

cc/ @zjrosen1

**Comment by goldblatt** [comment]
I'd also add I'm getting some off data in single county populations too (like Dekalb County GA has in the 2010 census like ~690,000 people and this search is showing 436k)

**Comment by mikelehen** [comment]
@goldblatt Maybe log a separate bug for that.  I think @zjrosen1 has diagnosed and fixed this.

**Comment by mikelehen** [comment]
@zjrosen1 fixed this.
