### ISSUE TITLE
"Poor compliance" graph extends farther than "strict compliance" or "available hospital beds"

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-projections#346]
*summary:* The graphs don't line up on the right side.  See screenshot.

*environment (device, browser, mobile / web):* chrome desktop (macOS)

*link:* https://staging.covidactnow.org/state/WA/county/king_county

*screenshot (you can copy/paste images directly in):*
![image](https://user-images.githubusercontent.com/206364/78212917-0d7cf280-7466-11ea-827a-9eba5544b8e1.png)

**Comment by jamestamplin** [comment]
It now seems to have inverted itself!

**Comment by mikelehen** [comment]
Obsolete.
