### ISSUE TITLE
Need an Explainer on what poor compliance means

### ISSUE THREAD

**Issue by goldblatt** [covid-projections/covid-projections#347]
I don't think it's explained in the doc or the chart what poor compliance means vs strict compliance. 

Some informative text about what that is on the chart label hover or at least details about it within the assumptions doc (maybe we need to just use the term 'poor compliance' for easy copy paste if it exists somewhere and i missed it) 

<img width="983" alt="Screen Shot 2020-04-02 at 1 24 51 AM" src="https://user-images.githubusercontent.com/6268375/78213494-d405b080-7480-11ea-80b0-7c55ff5cc0db.png">

**Comment by jamestamplin** [comment]
Related bug: 

https://github.com/covid-projections/covid-projections/issues/377

**Comment by mikelehen** [comment]
Obsolete.
