### ISSUE TITLE
Random Line Appears on Mobile

### ISSUE THREAD

**Issue by fridiculous** [covid-projections/covid-projections#349]
*summary:*
When I navigate to the main page on chrome on mobile web, and I scroll, I get a random line on the bottom for about 2 seconds. 

*expected result:*
There's no line that shows up

*actual result:*
There's a line that shows up while scrolling. before it disappears 3 seconds later.

*environment (device, browser, mobile / web):*
Chrome 
![IMG_7115](https://user-images.githubusercontent.com/1227514/78215579-a6167100-746c-11ea-918a-ab3aec76ff46.jpg)

*link:*
https://staging.covidactnow.org

*screenshot (you can copy/paste images directly in):*
![IMG_858AFFA54D33-1](https://user-images.githubusercontent.com/1227514/78215394-48822480-746c-11ea-9680-5e3bff53c559.jpeg)

**Comment by igorkofman** [comment]
Can't repro, fixed?
