### ISSUE TITLE
At larger screen size, the map button is always open 

### ISSUE THREAD

**Issue by goldblatt** [covid-projections/covid-projections#350]
The map in the corner is always open and there's no button, but on smaller screens its a button. I'd expect to have a button. 
![image](https://user-images.githubusercontent.com/6268375/78215658-036aec00-7486-11ea-81ec-ca4dab380bb5.png)

**Comment by jamestamplin** [comment]
I think this is works-as-intended.

PS HIIIIII SUSAN
