### ISSUE TITLE
Clicking on Miami-Dade county in FL does not work

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-projections#353]
*summary:* While the data is there, the website doesn't properly redirect to miami when it's clicked

*expected result:* You can view miami data

*actual result:*

![image](https://user-images.githubusercontent.com/1422280/78217979-06b4a680-748b-11ea-84b3-da79824fc021.png)

*environment (device, browser, mobile / web):* browser

*link:* http://localhost:3000/state/FL

*screenshot (you can copy/paste images directly in):*

**Comment by jamestamplin** [comment]
this now appears to be working!
