### ISSUE TITLE
Add Covid Act Now social media accounts to site

### ISSUE THREAD

**Issue by jessjoschwartz** [covid-projections/covid-projections#358]
*summary:*
We should have icons for Covid Act Now social media accounts on our website (not just icons for sharing). 

*expected result:*

*actual result:*

*environment (device, browser, mobile / web):*

*link:*

*screenshot (you can copy/paste images directly in):*

**Comment by mikelehen** [comment]
Dupe of https://github.com/covid-projections/covid-projections/issues/300 I think.
