### ISSUE TITLE
Pull quote on Endorsements has no credited endorser.

### ISSUE THREAD

**Issue by jessjoschwartz** [covid-projections/covid-projections#362]
*summary:*
Pull quote on Endorsements has no credited endorser. We need to list who said this quote to seem credible.

*expected result:*

*actual result:*

*environment (device, browser, mobile / web):*

*link:*
https://staging.covidactnow.org/endorsements

*screenshot (you can copy/paste images directly in):*
<img width="1163" alt="Screen Shot 2020-04-02 at 12 42 05 AM" src="https://user-images.githubusercontent.com/7066001/78222859-ccdba400-747a-11ea-8dcd-8a724b9c373d.png">

**Comment by thatneat** [comment]
Is the idea that all of the endorsers agree with the statement?
(I agree that the page came across as awkward but I'm not sure that just removing the quote is the solution)
