### ISSUE TITLE
Newsletter sign-up improvements

### ISSUE THREAD

**Issue by jessjoschwartz** [covid-projections/covid-projections#365]
*summary:*
Recommendations 
- If we can, put the newsletter sign-up above the fold somehow (maybe put it in the top header part of the page) and also in the footer. Robinhood has a clean footer example for their newsletter: https://robinhood.com/us/en/
- If we keep the newsletter sign-up on the page itself (not at the header or footer, I'd recommend changing the font. It's different than the fonts on the rest of the website and doesn't feel on-brand.
- Eliminate exclamation point from SUBSCRIBE! 

*expected result:*

*actual result:*

*environment (device, browser, mobile / web):*

*link:*

*screenshot (you can copy/paste images directly in):*

**Comment by jamestamplin** [comment]
I think @Jtensminger is working on this
