### ISSUE TITLE
For US / State toggle, change toggle color to something neutral (not red)

### ISSUE THREAD

**Issue by jessjoschwartz** [covid-projections/covid-projections#372]
*summary:*
For US / State toggle, change toggle color to something neutral (not red). It is confusing for states that are green since we are using green to convey Stay at Home, but the red text suggests otherwise.
![Uploading Screen Shot 2020-04-02 at 1.29.26 AM.png…]()

*expected result:*

*actual result:*

*environment (device, browser, mobile / web):*

*link:*

*screenshot (you can copy/paste images directly in):*

**Comment by jamestamplin** [comment]
changed to green!
