### ISSUE TITLE
Average Hospital Stay assumption states 4 days

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#378]
*summary:*
The Core Model Dynamics & Disease Timeline Assumptions states we use 4 days as the average hospital stay

*expected result:*
8 days (per comment from Ellie)

*actual result:*
4 days

*environment (device, browser, mobile / web):*
web

*link:*
https://data.covidactnow.org/Covid_Act_Now_Model_References_and_Assumptions.pdf

*screenshot (you can copy/paste images directly in):*
<img width="1014" alt="Screen Shot 2020-04-02 at 6 47 56 AM" src="https://user-images.githubusercontent.com/63055368/78256870-f4982f80-74ad-11ea-881a-f7fadf127b37.png">

**Comment by jamestamplin** [comment]
This has been updated
