### ISSUE TITLE
Different Graph Keys

### ISSUE THREAD

**Issue by DataDameX0** [covid-projections/covid-projections#380]
*summary:*
Different states have different "keys" for the graphs. (e.g. Social distancing v. 3 month stay at home strict v. 3 month stay at home non-strict). 

*expected result:*
All graph keys would look the same. 

*actual result:*
Not all graph keys look the same. 

*environment (device, browser, mobile / web):*
MacOS, Google Chrome, Web

*link:*
https://covidactnow.org/state/TN v. https://covidactnow.org/state/AL

*screenshot (you can copy/paste images directly in):*
![image](https://user-images.githubusercontent.com/20021348/78267622-2bce0700-74d5-11ea-9fdf-0f3780fa24b3.png)
(Two diff states). 

**NOTE:** This may be expected behavior for states who have issued "Stay at Home" orders v. states that haven't.

**Comment by jamestamplin** [comment]
Yes, this is working as intended, need to update what 'poor vs strict compliance' is, but that's tracked in another bug
