### ISSUE TITLE
reporting of "act-by" date for counties set to incorrect threshold

### ISSUE THREAD

**Issue by egraeden** [covid-projections/covid-projections#383]
*summary:* It looks in some of the county messaging that the “act-by” date is set incorrectly. 

*expected result:* Should be aligned with 2/2.5 weeks prior to hospital overloading

*actual result:*The timing here looks like it is aligned with the peak of the do-nothing scenario

*environment (device, browser, mobile / web):* all

*link:*

*screenshot (you can copy/paste images directly in):*
![image (13)](https://user-images.githubusercontent.com/63067330/78279518-e14c8a80-74d4-11ea-9663-1a1e29aeb5a0.png)

**Comment by jamestamplin** [comment]
This is actually a UI issue, not a data issue.

The hospitalizations is lined up with the end of the 'orange' section, which is the correct intervention.

We need to do this issue to make it clear that this county doesn't have a 'no intervention' scenario:

https://github.com/covid-projections/covid-projections/issues/367

**Comment by jamestamplin** [comment]
Closing this and tracking in another bug
