### ISSUE TITLE
Act now date range text color is confusing

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#386]
*summary:*
The act now date ranges are bolded in orange. The hospital overload is also orange. User are seeing the two and expecting the topic and are confused when the highlight different sets of dates.

*expected result:*
Same colors address same data point/ topic.

*actual result:*
Confusion due to different topics using the same color

*environment (device, browser, mobile / web):*
Web

*link:*
All states but specifically MO
https://covidactnow.org/state/MO

*screenshot (you can copy/paste images directly in):*
![Missouri](https://user-images.githubusercontent.com/63055368/78281033-e7d80380-74ce-11ea-9b3c-d22945e8cf5c.png)

**Comment by jamestamplin** [comment]
agreed - same as this one: 

https://github.com/covid-projections/covid-projections/issues/367

**Comment by jamestamplin** [comment]
closing as tracked in the other issue
