### ISSUE TITLE
Bring back the "back arrow" next to the logo on state / county pages

### ISSUE THREAD

**Issue by schlosser** [covid-projections/covid-projections#398]
*summary:* The back arrow is good, but we should have our branding somewhere there

*expected result:*

Something like this (see upper left):

 ![with-logo](https://user-images.githubusercontent.com/2433509/78315193-5e561f00-752a-11ea-9d23-4783dd4d2fec.png)

**Comment by thatneat** [comment]
Is the back arrow still around? I'm not seeing it anywhere.
![image](https://user-images.githubusercontent.com/3341011/78792398-eb073f80-7965-11ea-9e31-a0b94eacc46c.png)

**Comment by schlosser** [comment]
Might have gotten replaced instead of added on. This ticket can become "add arrow back"

**Comment by igorkofman** [comment]
I'm pretty sure it was a standard material ui back icon ala our search icon
