### ISSUE TITLE
Per-page Facebook/Twitter meta tags don't work

### ISSUE THREAD

**Issue by szhu** [covid-projections/covid-projections#450]
Originally posted here: https://github.com/covid-projections/covid-projections/issues/411#issuecomment-609671913, creating a new issue out of this.

*summary:*

 I don't think any of the page-specific Facebook/Twitter descriptions are working, since (1) Facebook and Twitter don't interpret `<meta>` tags in JavaScript and (2) we're not static/server-side rendering the `<meta>` tags.

*expected result:*

Sharing different pages shows different preview descriptions.

*actual result:*

Tested Facebook with the following methods:
1. <https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fcovidactnow.org%2Fus%2Fca>
2. Went to <https://covidactnow.org/us/ca> and clicked the FB share button
3. Sent myself <https://covidactnow.org/us/ca> in Facebook Messenger

For all 3 of these, only the title and description for the home page was returned.

Tested Twitter with the following methods:
1. Went to <https://covidactnow.org/us/ca> and clicked the Twitter share button
2. Posted <https://covidactnow.org/us/ca> on my Twitter feed and looked at the preview card

For both of these, no page-specific title was returned. The Twitter share button produced the title and description defined in `AppBar.js`, which is different from the home page's description but also is the same for every page.

*environment (device, browser, mobile / web):*

Tried on desktop, but I believe Facebook/Twitter scrape meta tags on their own servers, so this problem exists on every platform.

**Comment by mikelehen** [comment]
Done / Obsolete.
