### ISSUE TITLE
OpenGraph tags are incorrect and new screenshots aren't getting pickedup

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#472]
*summary:*
See https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fcovidactnow.org%2Fus%2Fca

Issues:
1. it complains about our image url for some reason
2. it has the super old screen screenshot - we need to maybe change the name or add a url param to get it out of cache
3. og:url is incorrect, should be ../us/ca in this case

*expected result:*

*actual result:*

*environment (device, browser, mobile / web):*

*link:*

*screenshot (you can copy/paste images directly in):*

**Comment by mikelehen** [comment]
Done / Obsolete.
