### ISSUE TITLE
Start generating  data needed to power "top counties to be overloaded" on homepage

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#479]
It should be a JSON file:

counties.overloaddate-top100.json

It should contain the information needed to power the UI feature:
[{state, countyName, fips, hospitalOverloadDate, hospitalizationPeakDate, aggregateDeaths}, ] 

Aggregate deaths is the final deaths number over the 3 months projection period.  
Generating this should probably be a post processing step executed by run.py / run.sh.

**Comment by goldblatt** [comment]
cool looking at a format like the following in order to match up with the api plans we have? 

`{
  "data": [
    {
      "stateName": "Alabama",
      "countyName": "Baldwin",
      "fips": "01003",
      "lastUpdatedDate": "4/9/2020 23:02",
      "projections": {
        "aggregateDeaths": 89,
        "hospitalBeds": {
          "peakShortfall": 3420,
          "peakDate": "2020-05-21T00:00:00",
          "shortageStartDate": "2020-05-01T00:00:00"
        }
      }
    },
    {
      "stateName": "Alabama",
      ...
     },
     ...
  ]
}`

**Comment by mikelehen** [comment]
Obsolete.
