### ISSUE TITLE
7-Day average of Cases in Charts different than avg used for Daily New Cases per 100k

### ISSUE THREAD

**Issue by akeybl** [covid-projections/covid-projections#5248]
Below screenshots taken at 8:10pm ET 3/1/21 from [https://covidactnow.org/us/district_of_columbia-dc/?s=29911850](https://covidactnow.org/us/district_of_columbia-dc/?s=29911850)
<img width="148" alt="image" src="https://user-images.githubusercontent.com/1084865/156275542-f3cab055-d976-4772-b7e1-885a1485bd99.png">
<img width="178" alt="image" src="https://user-images.githubusercontent.com/1084865/156275607-3af7a558-9357-4882-80b7-9dc71c8a188a.png">
<img width="234" alt="Screen Shot 2022-03-01 at 8 18 16 PM" src="https://user-images.githubusercontent.com/1084865/156276325-5cb71ca6-0ef6-4a5f-a6a1-426b0fb1e21f.png">

When using the methodology at [Risk levels & key metrics](https://covidactnow.org/covid-risk-levels-metrics#daily-new-cases)
![daily-new-cases-calculation](https://user-images.githubusercontent.com/1084865/156275844-294b8c93-070c-423b-8f82-b674a7bbda84.png)

Both https://api.covidactnow.org/v2/county/11001.json and https://api.covidactnow.org/v2/county/11001.timeseries.json have data up until 2/28 (**238** new cases, matching above screenshots). The data also matches a 7d moving average of **123.9**. They also note a population of 705749 (used below).

```
(238 + 0 + 0 + 112 + 100 + 48 + 369) / 7
----------------------------------------     =
              705749 / 100000

123.9
------     =
  7.1

17.6
```

Notice that the calculation is in agreement with the screenshotted charts, in that the 7d average of new cases is **123.9**. Note that the calculation is NOT in agreement with the presented 7d average of daily cases per 100k since **17.6 != 11.9**.

I don't think it has to do with newer data being available, since 2/28 is the latest available from NYT as well.

[https://github.com/nytimes/covid-19-data/commit/d926226498cb9ee0c2a5053dda582f6079286574](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-recent.csv)
**(Cached)** [us-counties-recent.csv](https://github.com/covid-projections/covid-projections/files/8165865/us-counties-recent.csv)

This doesn't appear to be an issue of the time window moving forward, though I could be wrong.

```
(0 + 238 + 0 + 0 + 112 + 100 + 48) / 7
----------------------------------------     =
              705749 / 100000

10.1
```

Again, **10.1 != 11.9**

Could this be due to improperly applying smoothing/prediction to the data?

**Comment by akeybl** [comment]
Alternatively, the population could be incorrect? By my calculation that would mean using a population of 1,041,176 instead of 705,749...

**Comment by akeybl** [comment]
@BrettBoval you were last to due issue triage work - can you help redirect?

**Comment by BrettBoval** [comment]
Hey. Thanks for the ping and the detailed issue report. Going forward, we also check data@actnowcoalition.org more frequently, but pinging both works.

We have code that back distributes data when there has been a reporting gap. So in the example you've given, some of those 369 cases on Feb 22 will be distributed back in time out of the averaging window. When I use 369/4 for that day's value (4 in the denominator because it has to cover that value plus three non-reporting days before), then the averages check out.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/20585842/156689065-da5f77b4-0a3e-4820-a6ab-feabe6a0b4e9.png">

We do that backfill because localities unfortunately skip reporting days in a non-periodic manner. In this case they skipped a day over the holidays and then just reported them all in one day when they get back. If they consistently skipped weekends that would be fine (since you'd drop out a blank weekend when you gained a new blank one), but we need to do something when they vary the gaps.

**Comment by akeybl** [comment]
Thanks for the explanation. Don't know how actively you all are doing development right now, but it would be great to add this info in some form to [Risk levels & key metrics](https://covidactnow.org/covid-risk-levels-metrics#daily-new-cases). Would also be great if I could reproduce the results - I'm blocked on knowing non-reporting days vs days with 0 cases.

How do you all make that determination? Is there a way for me to know within the API-returned json? Thanks in advance.

**Comment by smcclure17** [comment]
Hi, 

regarding,
>I'm blocked on knowing non-reporting days vs days with 0 cases.
How do you all make that determination? Is there a way for me to know within the API-returned json?

Admittedly, this is a problem that we don't have an elegant solution for. At the moment, we assume that "Covid is everywhere" and treat all zeros as non-reporting days. This has worked well throughout Omicron where case counts have been so high, but we may need to re-evaluate if/when case counts ever start trending towards zero.

In action, this means that,
- We treat all strings of non-trailing zeros as reporting gaps to backfill over, with the exception that we do not back distribute for reporting gaps larger than seven days long. 
- We remove any trailing zeros from the timeseries to preserve the last non-zero reported value. If a location reports at least ten days of consecutive trailing zeros, then we treat this data as actual zeros and we no longer remove them. 

I hope this is helpful, but please let me know if you have any further questions! I'm also willing to point you towards the source code that drives these calculations, too, if that would be of interest.

**Comment by BrettBoval** [comment]
I'm going to mark this as closed. Let me know @akeybl if you still have questions.
