### ISSUE TITLE
Where do state files in public/data/ come from?

### ISSUE THREAD

**Issue by saponas** [covid-projections/covid-projections#530]
I've been unable to generate the state json files that are in this repo's "public/data" directory by running the code in the repo covid-projections/covid-data-model against the data in repo covid-projections/covid-data-public.

I believe the current state of the website reflects the data currently in "/public/data" in the master branch. But the state json files I create with the covid-data-model code (and the data I see in some of the branches here, such as "update-data-4-6") have different values. For spot checking, I'll look at first week of July numbers for Oregon and see roughly double the value when I run the code versus what I see in this repo's public/data.

Apologies if I'm running the covid-data-model code incorrectly or misinterpreting that state level output from that code should go in public/data.

**Comment by igorkofman** [comment]
They were from a pyseir (new model) branch that just got merged into master yesterday.  Apologies for the confusion!
