### ISSUE TITLE
Counties have data, but show on map as having no data.

### ISSUE THREAD

**Issue by thatneat** [covid-projections/covid-projections#534]
## summary

some counties appear grey on the map, but actually have analyses.

## expected result

color of a county on the map matches the status of the county on the county-specific page

## actual result

sometimes there's a full projection/analysis for that county already

## environment

web

## link

https://covidactnow.org/us/wa/county/skamania_county

## screenshot

![image](https://user-images.githubusercontent.com/3341011/79269533-75adda00-7e51-11ea-85d6-56335d15aff9.png)

**Comment by zjrosen1** [comment]
cc @ghop02 this is due to the summary file not including the county fips code for a county that does have data

**Comment by ghop02** [comment]
Hmm I wonder if this is because we're generating the county/state files separately for the pyseir data.  Once the whole pipeline is in action I'd think this would get resolved? (but i haven't looked at it specifically)

**Comment by thatneat** [comment]
the map uses:

**Comment by mikelehen** [comment]
FWIW- Doesn't seem to be resolved. :-/
