### ISSUE TITLE
Feature Request: Make State Counties Map Bigger

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#542]
## summary
It is hard to see and select some counties on the state pop out map

## expected result
Easy to hover over, identify, and click on a county

E.g. I want to select San Francisco

## actual result
It is hard to find and click on San Francisco

## environment
Web

## link
covidactnow.org

## screenshot
<img width="1252" alt="Screen Shot 2020-04-16 at 10 39 07 AM" src="https://user-images.githubusercontent.com/63055368/79488470-9d767c80-7fce-11ea-8e35-fc1a67f3bad8.png">

**Comment by hannahleeCAN** [comment]
Users are continuing to write in about difficulties locating counties on the map, especially for Washington, DC (which many believe doesn't exist).

If we're enable zooming into the county map, it would also fix the following issue:

https://github.com/covid-projections/covid-projections/issues/696

**Comment by dannyOhNo** [comment]
County search box would help.
