### ISSUE TITLE
Incorrect Metro Area Bed Count

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#543]
@igorkofman James asked me to tag you

## summary
[from user]

From the main US map, I clicked on the state of Texas.  That page shows the overall state grid and then a map in the upper right corner with counties highlighted.  When I clicked on Williamson County, this is the link it goes to and shows all those counties combined.  

https://covidactnow.org/us/tx/county/bastrop_county_hays_county_travis_county_williamson_county
 
## expected result
3673 Total beds

Bastrop County - 6 beds
Hays County - 330 beds
Travis County - 2533 beds
Williamson County - 804 beds

## actual result
6 beds

## environment
Web

## link
https://covidactnow.org/us/tx/county/bastrop_county_hays_county_travis_county_williamson_county

## screenshot

![image](https://user-images.githubusercontent.com/63055368/79488866-4329eb80-7fcf-11ea-858b-42b3448dafbe.png)

**Comment by hannahleeCAN** [comment]
P.s. is the metro area feature is supposed to be live and available to users?

**Comment by hannahleeCAN** [comment]
Seeing this merge on the front end with the following counties as well

- Adams & Jefferson Counties - https://covidactnow.org/us/co/county/adams_county_jefferson_county
- Larimer & Weld Counties - https://covidactnow.org/us/co/county/larimer_county_weld_county
- Multnomah and Washington Counties - multnomah_county_washington_county

**Comment by mikelehen** [comment]
Obsolete.  Clicking on counties should no longer take you to combined pages.
