### ISSUE TITLE
County Estimated Deaths is greater that State Estimated Death

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#550]
## summary
Texas 3 months of strict stay at home is estimated to be 2000 people
Harris County's estimated death is 2.5x

I am also seeing this for California vs LA, and New York vs New York City

## expected result
Harris County should have fewer than 2000 estimated deaths

## actual result
Harris County's estimated deaths = 5000

## environment
*(device, browser, mobile / web)*
Web

## link
https://covidactnow.org/us/tx
https://covidactnow.org/us/tx/county/harris_county

## screenshot
<img width="925" alt="Screen Shot 2020-04-17 at 9 38 24 PM" src="https://user-images.githubusercontent.com/63055368/79628214-d0666080-80f3-11ea-9481-71d9de0fdb21.png">

<img width="936" alt="Screen Shot 2020-04-17 at 9 37 10 PM" src="https://user-images.githubusercontent.com/63055368/79628218-d3f9e780-80f3-11ea-9c1b-920dafd08c85.png">

**Comment by hannahleeCAN** [comment]
I'm guessing this is due to the inference model rolling out for states and not at the county level?

**Comment by mikelehen** [comment]
That's correct.  @igorkofman is working on a plan to fix this (basically enable inferencing for counties or turn them off)
