### ISSUE TITLE
Incomplete copy on current intervention for limited action - State

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/covid-projections#551]
## summary

The copy in _Current Intervention_ seems to be incomplete for the "Limited Action" case.

![image](https://user-images.githubusercontent.com/114084/79646315-c4ff4d80-8164-11ea-927a-68f367c3f74a.png)

## expected result

The phrase should be complete. I don't know what the copy should be

## actual result

The copy in _Current Intervention_ is incomplete for the "Limited Action" case.

## environment

- Web
- Chrome in Desktop

## link

- https://covidactnow.org/us/sd

## screenshot

![image](https://user-images.githubusercontent.com/114084/79646315-c4ff4d80-8164-11ea-927a-68f367c3f74a.png)

**Comment by mikelehen** [comment]
FYI- That text lives here: https://github.com/covid-projections/covid-projections/blob/ceca57be90e701cb3e5825dd52ef56637b4639c0/src/enums/interventions.js#L28

Looks like it got messed up here:
https://github.com/covid-projections/covid-projections/commit/e090b5e027ab8890805e34b96e632475ab9296b8#diff-313969129a79cffa5de570b09042ece6R28

Old text was “Public advocacy around “social distancing” and enhanced hygiene. Minimal mandated restrictions.”

**Comment by mikelehen** [comment]
Per @schlosser this section is going away soon.  Assigning to @schlosser for now.

**Comment by schlosser** [comment]
And it's gone!
