### ISSUE TITLE
Suffolk County, MA says "keep staying at home" but county shows up as red on county map

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-projections#556]
## summary
It seems like the county map is using the wrong projection to show the color for suffolk county. While there is a risk of overload with no interventions, the current intervention does not predict overload.

## expected result
suffolk county map color matches the intervention color on the page.

## actual result
suffolk county shows up as red on the county map

## environment
web

## link
https://covidactnow.org/us/ma/county/suffolk_county

## screenshot

![image](https://user-images.githubusercontent.com/1422280/79693643-c64e7a00-8239-11ea-9a06-4c7dc27dd57f.png)

**Comment by mikelehen** [comment]
I think I need to re-run the calculated-interventions script.

**Comment by mikelehen** [comment]
Fixed with #557.
