### ISSUE TITLE
Some counties show up as different color on main map vs state map

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#576]
## summary
Some counties show up as different color on main map vs state map
## expected result
https://covidactnow.org/us/ca/county/sierra_county is not colored orange on the home page

## actual result
https://covidactnow.org/us/ca/county/sierra_county is colored orange on the home page but not on the state page.  in actuality the county has no data at all.  In the pre-calculated county colorings it's not present so we must be using the fips code to pull a color from somewhere else somehow?  See USACountyMap 

## environment
*(device, browser, mobile / web)*

## screenshot
*(you can copy/paste images directly in)*

**Comment by mikelehen** [comment]
Investigating...

**Comment by mikelehen** [comment]
It's actually Nevada County that's colored wrong, and it's because we have a collision between state / county names.  Fixed in #577.
