### ISSUE TITLE
When you select one of the dark gray counties (have data but no model) the selected state is confusing

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#579]
## summary
When you select one of the dark gray counties (have data but no model) the selected state is confusing.  In particular because we just make opacity 0.5 in CountyMap and it makes the dark gray look like the light gray.  

Prolly the thing to do is either outline it or make it even darker gray in this case.  
I'd take any fix that makes the currently selected county clear!

## expected result
You can tell which county you selected 

## actual result
https://covidactnow.org/us/or/county/douglas_county 

## environment
*(device, browser, mobile / web)*

## screenshot
*(you can copy/paste images directly in)*

**Comment by yvonnehung** [comment]
Instead of blue selector, which covers the actual color, can we use an outline (3px, #000000)?  See mocks: https://www.figma.com/file/UUCr3ZpwaPV4o1KuGdSCNl/Covid?node-id=3334%3A19622

![image](https://user-images.githubusercontent.com/2531984/80540960-25f60500-895f-11ea-9f44-08e269a992e5.png)
