### ISSUE TITLE
Remove "Predictions not available" from the map view

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/covid-projections#581]
## summary

The legend "Predictions not available" is no longer relevant, as every state/county has predictions. Having the legend there might be confusing for the users (they might think it applies to the entire map).

## expected result

The legend "Predictions not available" shouldn't be visible if predictions are available for all the states in the map.

## actual result

The "Predictions not available" is showing, even if the predictions are available for all the states.

## environment

- Web, Chrome

## link

https://covidactnow.org/

## screenshot

![image](https://user-images.githubusercontent.com/114084/80040704-8b557c00-84af-11ea-83e7-51d638e186d6.png)

**Comment by mikelehen** [comment]
Gone!
