### ISSUE TITLE
Link in FAQ is incorrect

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#603]
## summary
The link to the Artis Ventures dashboard under "What’s the status of COVID vaccine and therapeutic development?" in the FAQ is incorrect; it's a duplicate of the link to the CDC list of symptoms. I think the link you meant to include there is https://t.co/0vNSpAUG3o

## expected result
https://www.av.co/covid

## actual result
https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html

## environment
Web

## link
https://covidactnow.org/faq

## screenshot
*(you can copy/paste images directly in)*

**Comment by mikelehen** [comment]
Thanks @hannahleeCAN!  I checked in the fix, which will show up on staging (https://staging.covidactnow.org/faq) momentarily.  It'll go to prod in the next few days.
