### ISSUE TITLE
Nevada testing data stops on April 12th but underlying datasource has data 

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#618]
https://staging.covidactnow.org/us/nv
https://data.covidactnow.org/snapshot/172/us/states/NV.OBSERVED_INTERVENTION.timeseries.json

https://covidtracking.com/data/state/nevada#historical

**Comment by mikelehen** [comment]
In general it seems like we're missing a lot of historical data.  E.g.:

* https://staging.covidactnow.org/us/wa only goes back to Apr 4, but https://covidtracking.com/data/state/washington#historical goes back to Jan 22.
* https://staging.covidactnow.org/us/ca goes back to Mar 27 but https://covidtracking.com/data/state/california#historical goes back to Mar 4.

Basically every state I checked was missing older historical data.

**Comment by mikelehen** [comment]
This has been resolved.
