### ISSUE TITLE
UX: Mobile view of Local Stats Summary looks jumbled

### ISSUE THREAD

**Issue by yvonnehung** [covid-projections/covid-projections#622]
## summary
The mobile view of the stats section on states/county pages looks jumbled. We can make the number font smaller and left align the text.

## expected result
![image](https://user-images.githubusercontent.com/2531984/80541405-f4ca0480-895f-11ea-927f-a20a6608407c.png)

## actual result
![Screenshot_20200428-144901](https://user-images.githubusercontent.com/2531984/80541279-bb919480-895f-11ea-9ad7-8271dbdacc36.png)

## environment
*(device, browser, mobile / web)* 
Mobile web

## screenshot

**Comment by mikelehen** [comment]
@goldblatt or @schlosser ?

**Comment by schlosser** [comment]
#626 will close this.
