### ISSUE TITLE
Change COVID to COVID-19

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#649]
## summary
References to COVID-19 are currently simply COVID

See AP Stylebook: https://www.apstylebook.com/topical_most_recent

## expected result
COVID-19

## actual result
COVID

## environment
Web

## link
https://staging.covidactnow.org/us/WY

## screenshot
<img width="669" alt="Screen Shot 2020-04-29 at 9 21 50 PM" src="https://user-images.githubusercontent.com/63055368/80671698-89675c00-8a5f-11ea-995f-6e1ecb828c80.png">

**Comment by mikelehen** [comment]
Maybe @schlosser can weigh in when he has time.  My assumption is that this is intentional, but I don't know the full rationale.

**Comment by mikelehen** [comment]
So JKT sent out a messaging doc over the weekend, where this is called out explicitly:

> When referring to the pathogen itself, we are going to use "COVID." All caps, like "NATO" or "SARS." No "-19." Just plain "COVID."

I can send you the doc if you don't have it. Else ping JKT / Anna for more details, I guess!
