### ISSUE TITLE
Predicted outcomes in [date] doesn't equal "in 90 days"

### ISSUE THREAD

**Issue by joshziman** [covid-projections/covid-projections#659]
## summary
Above the prediction table, the heading reads "Predicted outcomes by July 28, 2020 (90 days from now)". The date output is one day off. 

- Today is April 30
- 1 day from today is May 1
- 90 days from today is July 29
- On April 30, we should say that July 29 is in 90 days

## expected result
Predicted outcomes by July 28, 2020 (90 days from now)

## actual result
Predicted outcomes by July 29, 2020 (90 days from now)

## environment
*(device, browser, mobile / web)*

## link
[Date calculator
](https://www.timeanddate.com/date/dateadded.html?m1=4&d1=30&y1=2020&type=add&ay=&am=&aw=&ad=90&rec=)

## screenshot
![Real-time modeling and metrics to understand where we stand against COVID  - Covid Act Now](https://user-images.githubusercontent.com/4250157/80749793-a4cc7880-8aec-11ea-9111-75da42f37948.png)

**Comment by mikelehen** [comment]
So it's 90 days from when the chart day was last updated (which should have been in the last 2-3 days).

If we think this is a problem, I suggest we change it to "in 3 months" which is a little less specific.

**Comment by mikelehen** [comment]
To be extra clear, the API gives us 90 days out from when the API data was generated, so if it was generated 2 days ago, the furthest out we can give data for is 88 days.

**Comment by goldblatt** [comment]
alternatively we cold just say (~90 days from now)

**Comment by joshziman** [comment]
Good call. If that's the case, either `~90 days` or `in 3 months` both sounds like better options, and I think I slightly prefer `in 3 months`

**Comment by mikelehen** [comment]
👍 to "in 3 months"
