### ISSUE TITLE
Test Rate Calculation: Use weekly cumulatives.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-projections#706]
The way we calculate positive rate right now, it treats every daily positive rate equal regardless of how many tests there were that day.  That causes some weird stuff with e.g. Maine where they apparently report a small number of positive tests each day and then report all their negative tests only once a week. So most days their positive rate is 100% (or it would be if we didn't have a 7-day rolling average thrown in).

![image](https://user-images.githubusercontent.com/206364/80933033-cc367600-8d76-11ea-9012-c11517282123.png)

Our current logic calculates daily deltas from the positive/negative cumulative numbers, smooths them with a 7-day rolling average, and then divides to get the percentage.

I think instead we should calculate *weekly* deltas and divide them.  So basically each data point becomes `(last week of positives) / (last week of tests)`.  And this avoids the need for doing a rolling average.

**Comment by hannahleeCAN** [comment]
Users are writing in about Maine again. This time it's reporting 40% positive test rates. Any update on when this will be fixed?

**Comment by mikelehen** [comment]
Digging into this more, changing our logic doesn't help very much.  

The real problem is that Maine went 2 weeks without reporting any negative cases.  See https://covidtracking.com/data/state/maine#historical 

This means we really can't report a sensical test positive rate.

They have _finally_ reported their negative results, so the graph should fix itself today once we release the new data snapshot.

As a longer-term fix, I think we should maybe detect this case and just truncate the graph if there are no new negatives being reported, which means Maine's graph would have been stuck at May 6th for the last 2 weeks.
