### ISSUE TITLE
Add Additional Share Options

### ISSUE THREAD

**Issue by zjrosen1** [covid-projections/covid-projections#71]
See document for implementation

https://docs.google.com/document/d/1SC2IjcfFlZGf9bBvu27Zv-Fd3PXTilQCsKMQKQg8Rhk/edit#heading=h.nlwza26igxym

**Comment by Zacker** [comment]
This is amazing -- going to be a huge boost to growth.

Request: Can we please change the copy to what we standardized on for messaging? (this tests well in the wild)

"This is the point of no return for intervention to prevent <state_name’s> hospital system from being overloaded by Coronavirus: "
