### ISSUE TITLE
Hospitals overloaded line

### ISSUE THREAD

**Issue by jredding** [covid-projections/covid-projections#86]
When reviewing a chart the "hospitals overloaded" line does not adjust to a selected scenario. It is static for the "no action" scenario. 

Ideally this would adjust based on the scenario(s) selected OR some other design indicator demonstrating when hospital will become overloaded in the scenario.

**Comment by gsoltis** [comment]
I can take a stab at this.

**Comment by dopry** [comment]
@jredding  on  the state view?.  The hospitals overloaded line seems to be set based on the intervention that state is taking, so it should probably remain static.  However the line itself does seems to be off it should be at the intersection of the intervention and the available beds no?

![image](https://user-images.githubusercontent.com/387640/77838629-cb8d3d00-7143-11ea-9ad2-08f12f5a7af4.png)
