### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by jredding** [covid-projections/covid-projections#87]
Any new PR should run basic automated tests to ensure site basics and be expanded to run various regression tests. 

We can either have them run against the JS or do a full deployment (with refreshed data) to testing.covidactnow.org or to staging.covidactnow.org.

**Comment by zjrosen1** [comment]
@adpirz You have any experience with cypress?

**Comment by playermanny2** [comment]
I have some experience w/ cypress...can contribute to the basic framework to support this

**Comment by dopry** [comment]
@jredding #257 puts cypress in place so we have a framework for this. It should get the front end team started with testing. It'll be up to reviewers to ensure new tests are added as needed until we get some automated coverage testing in place.
