### ISSUE TITLE
Change us map from greytone to heatmap

### ISSUE THREAD

**Issue by zjrosen1** [covid-projections/covid-projections#92]
Change map to color code that maps to which intervention the state is doing (RED/YELLOW/BLUE) 

if red, days left for no-return.

**Comment by igorkofman** [comment]
best guess at bucketing https://docs.google.com/spreadsheets/d/1Hgt-3Y6Bs7n1K39pwDilHdFyXzqhMq6iqqYd0UAMe1k/edit#gid=0

**Comment by zjrosen1** [comment]
Measures from the Assumptions docs: https://docs.google.com/document/d/1ETeXAfYOvArfLvlxExE0_xrO5M4ITC0_Am38CRusCko/preview#

“Shelter-in-place”
Voluntary/VolunTold “shelter-in-place” community-wide home quarantine (especially firm for high-risk groups), shutdown of non-essential businesses, close schools, ban on events over 10 people, passive monitoring, public advocacy around social distancing and enhanced hygiene. Possibly closed borders or restricted travel. Public aid relief bill. Roll-out of free population-wide testing and quarantine, so that quarantines can be relaxed for those who are not infected.


Delay/Distancing
Voluntary “shelter-in-place” for high-risk groups, ban on events over 50 people, public advocacy around “social distancing” and enhanced hygiene, possible school closures, restricted travel, and passive monitoring. Roll-out of population-wide testing and quarantine, so that quarantines can be relaxed for those who are not infected.


Do Nothing
current historical trends continue

**Comment by igorkofman** [comment]
👏
