### ISSUE TITLE
Change text in Social Share on state page

### ISSUE THREAD

**Issue by Zacker** [covid-projections/covid-projections#97]
The social share feature is huge. Going to be a big boost to drive awareness.

Request: Can we please change the copy to what we standardized on for messaging? (this tests well in the wild)

`"This is the point of no return for intervention to prevent <state_name’s> hospital system from being overloaded by Coronavirus: "`

**Comment by Fiskell** [comment]
https://github.com/covid-projections/covid-projections/pull/101
